export enum RoleEnum {
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
  REPORT_MANAGER = "REPORT_MANAGER",
  REPORT_VIEWER = "REPORT_VIEWER",
  GENERAL_VIEWER = "GENERAL_VIEWER",
  MAINTENANCE_MANAGER = "MAINTENANCE_MANAGER",
  MAINTENANCE_CONSULTANT = "MAINTENANCE_CONSULTANT",
  TIRE_CONSULTANT = "TIRE_CONSULTANT",
  PARTS_CONSULTANT = "PARTS_CONSULTANT",
  PARTS_MANAGER = "PARTS_MANAGER",
  GUEST = "GUEST"
}

export type TRole = keyof typeof RoleEnum;