export enum SubjectEnum {
  Axle = 'Axle',
  Box = 'Box',
  Company = 'Company',
  Employee = 'Employee',
  Event = 'Event',
  User = 'User',
  Part = 'Part',
  PartCategory = 'PartCategory',
  Project = 'Project',
  Fleet = 'Fleet',
  Job = 'Job',
  Carrier = 'Carrier',
  Service = 'Service',
  Checklist = 'Checklist',
  Part_Request = 'PartRequest',
  Work_Order = "WorkOrder",
  Maintenance = "Maintenance",
  Membership = "Membership",
  Note = "Note",
  WaitingParts = "WaitingParts",
  ServiceAssigment = "ServiceAssigment",
  Trailer = "Trailer",
  Template_Checklist = "TemplateChecklist",
  Tire = "Tire",
  Vehicle = "Vehicle",
  WorkOrder = "WorkOrder",
}

export type TSubject = keyof typeof SubjectEnum;